;	TITLE	BBC BASIC (C) R.T.RUSSELL 1981-2024
;
;RAM MODULE FOR BBC BASIC INTERPRETER
;FOR USE WITH VERSION 5.0 OF BBC BASIC
;(C) COPYRIGHT R.T.RUSSELL 1981-2024
;
	PUBLIC	ACCS
	PUBLIC	BUFFER
	PUBLIC	ONERSP
	PUBLIC	LIBASE
	PUBLIC	PAGE
	PUBLIC	LOMEM
	PUBLIC	FREE
	PUBLIC	HIMEM
	PUBLIC	RANDOM
	PUBLIC	COUNT
	PUBLIC	WIDTH
	PUBLIC	ERL
	PUBLIC	ERR
	PUBLIC	ERRTRP
	PUBLIC	ERRTXT
	PUBLIC	TRACEN
	PUBLIC	AUTONO
	PUBLIC	INCREM
	PUBLIC	LISTON
	PUBLIC	DATPTR
	PUBLIC	FNPTR
	PUBLIC	PROPTR
	PUBLIC	STAVAR
	PUBLIC	OC
	PUBLIC	PC
	PUBLIC	DYNVAR
	PUBLIC	CURLIN
	PUBLIC	USER
;
;n.b. ACCS, BUFFER & STAVAR must be on page boundaries.
;

START_OF_DATA: NOP
ACCS	EQU START_OF_DATA + 0FFH & 0FF00H	;4B00H STRING ACCUMULATOR
BUFFER	EQU	ACCS   + 100H		;STRING INPUT BUFFER
STAVAR	EQU	BUFFER + 100H		;STATIC VARIABLES
OC		EQU	STAVAR+14*4			;CODE ORIGIN (O%)
PC		EQU	STAVAR+15*4			;PROGRAM COUNTER (P%)
DYNVAR	EQU STAVAR + 27*4  		;DYN. VARIABLE POINTERS
START	EQU DYNVAR + 54*2
FNPTR	EQU START + 2			;DYN. FUNCTION POINTER
PROPTR	EQU START + 4 			;DYN. PROCEDURE POINTER
;
PAGE	EQU START + 6			;START OF USER PROGRAM
LOMEM   EQU START + 8 			;START OF DYN. STORAGE
FREE	EQU START + 10 			;FIRST FREE-SPACE BYTE
HIMEM	EQU START + 12 			;FIRST BYTE ABOVE STACK
LIBASE	EQU START + 14 			;START OF FIRST LIBRARY
;
TRACEN	EQU START + 16 			;TRACE FLAG AND NUMBER
AUTONO	EQU START + 18 			;AUTO FLAG AND NUMBER
ERRTRP	EQU START + 20 			;ON ERROR STMT POINTER \
ONERSP	EQU START + 22 			;ON ERROR LOCAL STKPTR /
ERRTXT	EQU START + 24 			;ERROR MESSAGE POINTER
DATPTR	EQU START + 26 			;DATA POINTER
ERL		EQU START + 28 			;LINE NO OF LAST ERROR
CURLIN	EQU START + 30 			;POINTER TO CURRENT LINE
RANDOM:	EQU START + 32 			;RANDOM NUMBER
COUNT:	EQU START + 37 			;PRINT POSITION
WIDTH	EQU START + 38			;PRINT WIDTH
ERR		EQU START + 39 			;ERROR NUMBER
LISTON	EQU START + 40 			;LISTO & OPT FLAG
INCREM	EQU START + 41 			;AUTO INCREMENT
;
USER	EQU START + 42			; START OF USER SPACE BASIC PROGRAM	






;ACCS:	DEFS	256		;STRING ACCUMULATOR
;BUFFER:	DEFS	256		;STRING INPUT BUFFER
;STAVAR:	DEFS	27*4		;STATIC VARIABLES
;OC	EQU	STAVAR+15*4	;CODE ORIGIN (O%)
;PC	EQU	STAVAR+16*4	;PROGRAM COUNTER (P%)
;OC:		DEFS	4
;PC:		DEFS	4
;DYNVAR:	DEFS	54*2		;DYN. VARIABLE POINTERS
;FNPTR:	DEFS	2		;DYN. FUNCTION POINTER
;PROPTR:	DEFS	2		;DYN. PROCEDURE POINTER
;
;PAGE:	DEFS	2		;START OF USER PROGRAM
;LOMEM:	DEFS	2		;START OF DYN. STORAGE
;FREE:	DEFS	2		;FIRST FREE-SPACE BYTE
;HIMEM:	DEFS	2		;FIRST BYTE ABOVE STACK
;LIBASE:	DEFS	2		;START OF FIRST LIBRARY
;
;TRACEN:	DEFS	2		;TRACE FLAG AND NUMBER
;AUTONO:	DEFS	2		;AUTO FLAG AND NUMBER
;ERRTRP:	DEFS	2		;ON ERROR STMT POINTER \
;ONERSP:	DEFS	2		;ON ERROR LOCAL STKPTR /
;ERRTXT:	DEFS	2		;ERROR MESSAGE POINTER
;DATPTR:	DEFS	2		;DATA POINTER
;ERL:	DEFS	2		;LINE NO OF LAST ERROR
;CURLIN:	DEFS	2		;POINTER TO CURRENT LINE
;RANDOM:	DEFS	5		;RANDOM NUMBER
;COUNT:	DEFS	1		;PRINT POSITION
;WIDTH:	DEFS	1		;PRINT WIDTH
;ERR:	DEFS	1		;ERROR NUMBER
;LISTON:	DEFS	1		;LISTO & OPT FLAG
;INCREM:	DEFS	1		;AUTO INCREMENT
;
;USER:	DEFB 	0DH
