;	TITLE	BBC BASIC (C) R.T.RUSSELL 1981-2024
;
;RAM MODULE FOR BBC BASIC INTERPRETER
;FOR USE WITH VERSION 5.0 OF BBC BASIC
;(C) COPYRIGHT R.T.RUSSELL 1981-2024
;
	PUBLIC	ACCS
	PUBLIC	BUFFER
	PUBLIC	ONERSP
	PUBLIC	LIBASE
	PUBLIC	PAGE
	PUBLIC	LOMEM
	PUBLIC	FREE
	PUBLIC	HIMEM
	PUBLIC	RANDOM
	PUBLIC	COUNT
	PUBLIC	WIDTH
	PUBLIC	ERL
	PUBLIC	ERR
	PUBLIC	ERRTRP
	PUBLIC	ERRTXT
	PUBLIC	TRACEN
	PUBLIC	AUTONO
	PUBLIC	INCREM
	PUBLIC	LISTON
	PUBLIC	DATPTR
	PUBLIC	FNPTR
	PUBLIC	PROPTR
	PUBLIC	STAVAR
	PUBLIC	OC
	PUBLIC	PC
	PUBLIC	DYNVAR
	PUBLIC	CURLIN
	PUBLIC	USER
;
;n.b. ACCS, BUFFER & STAVAR must be on page boundaries.
;
ACCS:	DEFS	256		;STRING ACCUMULATOR
BUFFER:	DEFS	256		;STRING INPUT BUFFER
STAVAR:	DEFS	27*4		;STATIC VARIABLES
OC	EQU	STAVAR+15*4	;CODE ORIGIN (O%)
PC	EQU	STAVAR+16*4	;PROGRAM COUNTER (P%)
DYNVAR:	DEFS	54*2		;DYN. VARIABLE POINTERS
FNPTR:	DEFS	2		;DYN. FUNCTION POINTER
PROPTR:	DEFS	2		;DYN. PROCEDURE POINTER
;
PAGE:	DEFS	2		;START OF USER PROGRAM
LOMEM:	DEFS	2		;START OF DYN. STORAGE
FREE:	DEFS	2		;FIRST FREE-SPACE BYTE
HIMEM:	DEFS	2		;FIRST BYTE ABOVE STACK
LIBASE:	DEFS	2		;START OF FIRST LIBRARY
;
TRACEN:	DEFS	2		;TRACE FLAG AND NUMBER
AUTONO:	DEFS	2		;AUTO FLAG AND NUMBER
ERRTRP:	DEFS	2		;ON ERROR STMT POINTER \
ONERSP:	DEFS	2		;ON ERROR LOCAL STKPTR /
ERRTXT:	DEFS	2		;ERROR MESSAGE POINTER
DATPTR:	DEFS	2		;DATA POINTER
ERL:	DEFS	2		;LINE NO OF LAST ERROR
CURLIN:	DEFS	2		;POINTER TO CURRENT LINE
RANDOM:	DEFS	5		;RANDOM NUMBER
COUNT:	DEFS	1		;PRINT POSITION
WIDTH:	DEFS	1		;PRINT WIDTH
ERR:	DEFS	1		;ERROR NUMBER
LISTON:	DEFS	1		;LISTO & OPT FLAG
INCREM:	DEFS	1		;AUTO INCREMENT
;
USER:	DEFS 	0
